name: Trigger Deployment
on:
  push:
    branches:
      - fylepod_design_main
jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Repository Workflow
        run: |
          echo test
          curl -X POST http://104.42.132.14:8080/view/Medicodio%20Dev/job/Relayzen%20DEV%20FE/build?token=Relayzen_DEV_FE \
          --user "dev-team:${{ secrets.JENKINS_TOKEN}}"